services:
  synthwave:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: synthwave-dev
    restart: unless-stopped
    ports:
      - "${SYNTHWAVE_PORT}:5000"
    volumes:
      - ${MUSIC_PATH}:/music
      - ${BINARY_PATH}:/binary
      - ${PLAYLISTS_PATH}:/playlists
      - ${CONFIG_PATH}:/app/config
      - ${LOGS_PATH}:/app/logs
    environment:
      - TZ=${TZ}
      - FLASK_ENV=development
    networks:
      - synthwave-network

networks:
  synthwave-network:
    driver: bridge
