services:
  synthwave:
    image: ghcr.io/pranavverma-droid/synthwave:latest
    container_name: synthwave
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /data/songs/All Songs:/music
      - /data/songs/Binary:/binary
      - /data/songs/Playlists/1:/playlists
      - ../config.json:/app/config.json
    environment:
      - TZ=UTC
      - FLASK_ENV=production
    networks:
      - synthwave-network

networks:
  synthwave-network:
    driver: bridge
